### ISSUE TITLE
Traceback | 'super' object is not an iterator in util

### ISSUE THREAD

**Issue by twschum** [twschum/mix-mind#39]
Happens on csv upload
```
INFO:werkzeug:127.0.0.1 - - [09/Jan/2020 17:12:47] "POST /manage/ingredients HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/tim/mix-mind/venv/lib/python3.7/site-packages/flask_security/decorators.py", line 216, in decorated_view
    return fn(*args, **kwargs)
  File "/Users/tim/mix-mind/mixmind/views.py", line 386, in decorated_function
    return f(*args, **kwargs)
  File "/Users/tim/mix-mind/mixmind/views.py", line 487, in ingredient_stock
    replace_existing=upload_form.replace_existing.data)
  File "/Users/tim/mix-mind/mixmind/barstock.py", line 80, in load_from_csv
    for row in reader:
  File "/Users/tim/mix-mind/mixmind/util.py", line 379, in __next__
    row = next(super(UnicodeDictReader, self))
TypeError: 'super' object is not an iterator

```

**Comment by twschum** [comment]
Duplicated by #42, fixed by #43
