### ISSUE TITLE
Traceback | Writeerror on /

### ISSUE THREAD

**Issue by twschum** [twschum/mix-mind#46]
```
2020-03-25 21:18:49,694: Exception on / [GET]
Traceback (most recent call last):
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 726, in _getter
    getter = self._metadata._getter
AttributeError: 'NoneType' object has no attribute '_getter'
**NO MATCH**
During handling of the above exception, another exception occurred:
**NO MATCH**
Traceback (most recent call last):
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/twschum/mix-mind/mixmind/views.py", line 131, in browse
    to_html=True, order_link=True, convert_to=current_bar.convert, condense_ingredients=current_bar.summarize)
  File "/home/twschum/mix-mind/mixmind/views.py", line 69, in recipes_from_options
    recipes, excluded = filter_recipes(mms.processed_recipes(current_bar), filter_options, union_results=bool(filter_options.search))
  File "/home/twschum/mix-mind/mixmind/configuration_management.py", line 74, in processed_recipes
    self.generate_recipes(bar)
  File "/home/twschum/mix-mind/mixmind/configuration_management.py", line 88, in generate_recipes
    for name, recipe in list(self.base_recipes.items())]
  File "/home/twschum/mix-mind/mixmind/configuration_management.py", line 88, in <listcomp>
    for name, recipe in list(self.base_recipes.items())]
  File "/home/twschum/mix-mind/mixmind/recipe.py", line 103, in generate_examples
    example_kinds = barstock.get_all_kind_combinations((i.specifier for i in ingredients))
  File "/home/twschum/mix-mind/mixmind/barstock.py", line 119, in get_all_kind_combinations
    kind_lists = [[b.Kind for b in self.slice_on_type(i)] for i in specifiers]
  File "/home/twschum/mix-mind/mixmind/barstock.py", line 119, in <listcomp>
    kind_lists = [[b.Kind for b in self.slice_on_type(i)] for i in specifiers]
  File "/home/twschum/mix-mind/mixmind/barstock.py", line 169, in slice_on_type
    return Ingredient.query.filter(filter_).all()
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3161, in all
    return list(self)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 65, in instances
    for query_entity in query._entities
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 65, in <listcomp>
    for query_entity in query._entities
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4182, in row_processor
    polymorphic_discriminator=self._polymorphic_discriminator,
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 405, in _instance_processor
    getter = result._getter(col, False)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 728, in _getter
    return self._non_result(None)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1170, in _non_result
    "This result object does not return rows. "
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
2020-03-25 21:18:49,730: OSError: write error
```

**Comment by twschum** [comment]
Could not reproduce
