### ISSUE TITLE
Traceback | ValueError multiple entries on get_ingredient_row()

### ISSUE THREAD

**Issue by twschum** [twschum/mix-mind#47]
```
Exception on / [GET]
Traceback (most recent call last):
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/twschum/mix-mind/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/twschum/mix-mind/mixmind/views.py", line 131, in browse
    to_html=True, order_link=True, convert_to=current_bar.convert, condense_ingredients=current_bar.summarize)
  File "/home/twschum/mix-mind/mixmind/views.py", line 69, in recipes_from_options
    recipes, excluded = filter_recipes(mms.processed_recipes(current_bar), filter_options, union_results=bool(filter_options.search))
  File "/home/twschum/mix-mind/mixmind/configuration_management.py", line 74, in processed_recipes
    self.generate_recipes(bar)
  File "/home/twschum/mix-mind/mixmind/configuration_management.py", line 88, in generate_recipes
    for name, recipe in list(self.base_recipes.items())]
  File "/home/twschum/mix-mind/mixmind/configuration_management.py", line 88, in <listcomp>
    for name, recipe in list(self.base_recipes.items())]
  File "/home/twschum/mix-mind/mixmind/recipe.py", line 113, in generate_examples
    example.std_drinks += ingredient.get_std_drinks(kind, barstock)
  File "/home/twschum/mix-mind/mixmind/recipe.py", line 346, in get_std_drinks
    abv = barstock.get_kind_abv(util.IngredientSpecifier(self.specifier.ingredient, kind))
  File "/home/twschum/mix-mind/mixmind/barstock.py", line 124, in get_kind_abv
    return self.get_kind_field(ingredient, 'ABV')
  File "/home/twschum/mix-mind/mixmind/barstock.py", line 136, in get_kind_field
    return self.get_ingredient_row(ingredient)[field]
  File "/home/twschum/mix-mind/mixmind/barstock.py", line 143, in get_ingredient_row
    raise ValueError('{} has multiple entries in the input data!'.format(ingredient.__repr__()))
ValueError: Scotch whisky:Laphroaig 10 CS Batch #10 has multiple entries in the input data!
```

**Comment by twschum** [comment]
This happened after placing an order, and on the confirmation page, trying to switch bars
